// <auto-generated />
using System;
using CerezoJose_Progreso1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CerezoJose_Progreso1.Migrations
{
    [DbContext(typeof(CerezoJose_Progreso1Context))]
    [Migration("20241030134014_Telefono añadido a usuario")]
    partial class Telefonoañadidoausuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CerezoJose_Progreso1.Models.JoseCerezo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadHermanos")
                        .HasColumnType("int");

                    b.Property<bool>("EsHombre")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("SaldoBancario")
                        .HasColumnType("float");

                    b.Property<int>("TelefonoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TelefonoId");

                    b.ToTable("JoseCerezo");
                });

            modelBuilder.Entity("CerezoJose_Progreso1.Models.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Telefono");
                });

            modelBuilder.Entity("CerezoJose_Progreso1.Models.JoseCerezo", b =>
                {
                    b.HasOne("CerezoJose_Progreso1.Models.Telefono", "Telefono")
                        .WithMany()
                        .HasForeignKey("TelefonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telefono");
                });
#pragma warning restore 612, 618
        }
    }
}
